---
- name: Common stuff
  hosts: all
  remote_user: root
  become: true

  roles:
    - common

- name: Install nginx and scabot on the master
  hosts: master
  remote_user: root
  become: true

  roles:
    - nginx
    - scabot

- name: Configure a publisher worker
  hosts: worker
  remote_user: root
  become: true

  roles:
    - worker
