---
# run with `ansible-playbook site.yml`
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # ami-6d03030d --> https://wiki.debian.org/Cloud/AmazonEC2Image/Stretch
    # the ip addresses are just for correlation with the config files under roles/jenkins/files/nodes/
    - instances:  [
        {name: "jenkins-master", instance_type: "m4.large", image: "ami-6d03030d", network_interface: "eni-f9c808fc", instance_profile_name: "JenkinsMaster",  groupname: ["master"], public_ip: "54.67.111.226", private_ip: "172.31.2.1", volumes: ["{{ec2_vol_jenkins}}"]}, # , "{{ec2_vol_artifactory}}"
        {name: "jenkins-worker-ubuntu-publish",  instance_type: "c4.xlarge" , image: "ami-6d03030d", network_interface: "eni-f00ecef5", instance_profile_name: "JenkinsWorkerPublish",  groupname: [ "worker", "publisher" ], volumes: ["{{ec2_vol_worker}}"], public_ip: "54.67.33.167",  private_ip: "172.31.2.2"}
        # {name: "jenkins-worker-behemoth-1",      instance_type: "c4.2xlarge", image: "ami-6d03030d", network_interface: "eni-0e0ccc0b", instance_profile_name: "JenkinsWorker",  groupname: ["worker"], public_ip: "54.153.2.9",    private_ip: "172.31.2.3"},
        # {name: "jenkins-worker-behemoth-2",      instance_type: "c4.2xlarge", image: "ami-6d03030d", network_interface: "eni-8f0dcd8a", instance_profile_name: "JenkinsWorker",  groupname: ["worker"], public_ip: "54.153.1.99",   private_ip: "172.31.2.4"}
      ]
        #     {name: "jenkins-worker-windows-publish", instance_type: "c4.xlarge",  image: "TODO",         network_interface: "eni-78a74a79", instance_profile_name: "JenkinsWorker",  public_ip: "54.183.156.89", private_ip: "172.31.2.5"}
  tasks:
    - include_tasks: roles/common/tasks/ec2.yml

- name: Common stuff
  hosts: all
  remote_user: "{{admin_user}}"
  become: true

  roles:
    - common

- name: Install & configure nginx, artifactory, jenkins and scabot on the master
  hosts: master
  gather_facts: yes
  remote_user: "{{admin_user}}"
  become: true

  roles:
    - nginx
    # - artifactory
    - jenkins
    # - scabot

- name: Configure workers
  hosts: worker
  gather_facts: yes
  remote_user: "{{admin_user}}"
  become: true
  vars:
    - jenkins_home: "/home/jenkins"
  roles:
    - worker
