---
- name: Common stuff
  hosts: all
  remote_user: root
  become: true

  roles:
    - common

- name: Install nginx, artifactory and scabot on the master
  hosts: master
  gather_facts: yes
  remote_user: root
  become: true

  roles:
    - nginx
    - artifactory
    - jenkins
    # - scabot

- name: Configure a publisher worker
  hosts: worker
  gather_facts: yes
  remote_user: root
  become: true

  roles:
    - worker
