---
- name: Give adriaanm's github pubkey admin access
  become: true
  authorized_key:
    user: "{{ admin_user }}"
    state: present
    key: https://github.com/adriaanm.keys

- name: Add repo for Java 9 backports
  become: true
  apt_repository: repo='deb http://ftp.debian.org/debian stretch-backports main'

- name: Install openjdk
  become: true
  apt: name={{item}} state=installed
  with_items:
       # - openjdk-6-jdk
       # - openjdk-7-jdk
       - openjdk-8-jdk
       - openjdk-9-jdk

- name: Copy jvm-select script
  become: true
  copy: src=jvm-select dest=/usr/local/share/jvm/ owner=root mode=755


- name: Install basic packages
  become: true
  apt: name={{item}} state=installed
  with_items:
       - ant
       - ant-contrib
       - ant-optional
       - maven
       - s3curl
       - tofrodos

- name: Create sbt launcher path
  become: true
  file: path="{{sbt_launcher_path}}" state=directory

- name: Download sbt launcher
  become: true
  get_url:
      url: "https://repo.lightbend.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/{{ sbt_version }}/sbt-launch.jar"
      dest: "{{sbt_launcher_path}}"
      owner: root
      mode: 755
