---
- name: Give adriaanm's github pubkey admin access
  become: true
  authorized_key:
    user: "{{ admin_user }}"
    state: present
    key: https://github.com/adriaanm.keys

# - name: Add repo with older Java
#   become: true
#   apt_repository: repo='ppa:openjdk-r/ppa'
#
# - name: Install java 7
#   become: true
#   apt: name=openjdk-7-jdk state=present

- name: Install java 8
  become: true
  apt: name=openjdk-8-jdk state=present

- name: Install java 9
  become: true
  apt: name=openjdk-9-jdk-headless state=present # https://bugs.launchpad.net/ubuntu/+source/openjdk-9/+bug/1593191
