---
- name: Give adriaanm's github pubkey admin access
  become: true
  authorized_key:
    user: "{{ admin_user }}"
    state: present
    key: https://github.com/adriaanm.keys

- name: Add repo for Java 9 backports
  become: true
  apt_repository: repo='deb http://ftp.debian.org/debian stretch-backports main'
#
# - name: Install java 6
#   become: true
#   apt: name=openjdk-6-jdk state=present
#
# - name: Install java 7
#   become: true
#   apt: name=openjdk-7-jdk state=present

- name: Install java 8
  become: true
  apt: name=openjdk-8-jdk state=present

- name: Install java 9
  become: true
  apt: name=openjdk-9-jdk state=present

- name: Copy jvm-select script
  become: true
  copy: src=jvm-select dest=/usr/local/share/jvm/ owner=root mode=755
